# Generated by Django 6.0 on 2026-01-03 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Условие задачи')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('difficulty', models.IntegerField(default=800, verbose_name='Сложность (например, 800)')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название контеста')),
                ('description', models.TextField(blank=True, verbose_name='Описание/Правила')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время завершения')),
                ('problems', models.ManyToManyField(blank=True, related_name='contests', to='archive.problem')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disqualified', models.BooleanField(default=False, verbose_name='Дисквалифицирован')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина бана')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=100, verbose_name='Ответ участника')),
                ('solution_text', models.TextField(blank=True, null=True, verbose_name='Решение')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верно?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.problem')),
            ],
        ),
    ]
