# Generated by Django 6.0 on 2026-01-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название ранга')),
                ('min_rating', models.IntegerField(default=0, verbose_name='Минимальный рейтинг для получения')),
                ('color_code', models.CharField(default='#808080', max_length=7, verbose_name='Цвет (HEX, например #FF0000)')),
            ],
            options={
                'verbose_name': 'Настройка ранга',
                'verbose_name_plural': 'Настройки рангов',
                'ordering': ['min_rating'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
