# Generated by Django 6.0 on 2026-01-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty_level',
            field=models.CharField(choices=[('bg-info text-dark', 'Baby (Голубой)'), ('bg-success', 'Easy (Зеленый)'), ('bg-primary', 'Normal (Синий)'), ('bg-warning text-dark', 'Hard (Желтый)'), ('bg-danger', 'Legendary (Красный)'), ('bg-dark', 'X-Level (Черный)')], default='bg-primary', max_length=50, verbose_name='Цветовой уровень'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(default=0, verbose_name='Сложность (например, 800)'),
        ),
    ]
