# Generated by Django 6.0 on 2026-02-27 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_problem_difficulty_level_alter_problem_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'verbose_name': 'Contest', 'verbose_name_plural': 'Contests'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['min_rating'], 'verbose_name': 'Rank Setting', 'verbose_name_plural': 'Rank Settings'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description/Rules'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Contest Title'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='correct_answer',
            field=models.CharField(max_length=100, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(verbose_name='Problem Statement'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(default=0, verbose_name='Difficulty Rating'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty_level',
            field=models.CharField(choices=[('bg-info text-dark', 'Baby (Blue)'), ('bg-success', 'Easy (Green)'), ('bg-primary', 'Normal (Blue)'), ('bg-warning text-dark', 'Hard (Yellow)'), ('bg-danger', 'Legendary (Red)'), ('bg-dark', 'X-Level (Black)')], default='bg-primary', max_length=50, verbose_name='Color Level'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_disqualified',
            field=models.BooleanField(default=False, verbose_name='Disqualified'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ban Reason'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='color_code',
            field=models.CharField(default='#808080', max_length=7, verbose_name='Color (HEX)'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_rating',
            field=models.IntegerField(default=0, verbose_name='Minimum Rating'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Rank Title'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='solution_text',
            field=models.TextField(blank=True, null=True, verbose_name='Solution/Thinking'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user_answer',
            field=models.CharField(max_length=100, verbose_name='User Answer'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('related_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='archive.problem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='archive.blogpost')),
            ],
        ),
    ]
